server:
  port: 9010

spring:
  datasource:
    url: jdbc:mysql://localhost:3336/ms-email
    username: root
    password: root

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

  mail:
    host: http://****.com.br
    port: 587
    username: user****
    password: pass*****
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  rabbitmq:
    host: http://****.com.br
    queue: email-request-queue
    username: username
    password: secret
    template:
      retry:
        enabled: true
        initial-interval: 2s

broker:
  queue:
    email:
      name: email-request-queue