version: "3.5"

services:
  rabbitmq:
    image: rabbitmq:3.13.6-management-alpine
    container_name: rabbitmq-sisavn
    restart: always
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./dados:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=sislogweb
      - RABBITMQ_DEFAULT_PASS=gafanhoto